### ISSUE TITLE
run demo.lua error

### ISSUE THREAD

**Issue by northeastsquare** [facebookresearch/multipathnet#1]
Hello, after installation, I ran demo.lua, I got:
/home/sam/torch/install/bin/luajit: ./deepmask/InferSharpMask.lua:67: attempt to get length of field 'refs' (a nil value)
stack traceback:
	./deepmask/InferSharpMask.lua:67: in function '__init'
	/home/sam/torch/install/share/lua/5.1/torch/init.lua:91: in function </home/sam/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'Infer'
	./demo.lua:54: in main chunk
	[C]: in function 'dofile'
	.../sam/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by szagoruyko** [comment]
cc @poliveirap can you take a look?

**Comment by poliveirap** [comment]
hm, weird. It does work here. 
it seems that the path to sharpmask.t7 is not correct...? 
What is the exact command you using to run the demo? Where is sharpmask.t7 located in you directory?

**Comment by northeastsquare** [comment]
/home/sam/src/multipathnet/data/models/sharpmask.t7

**Comment by poliveirap** [comment]
I guess this error would appear if you use deepmask.t7 instead of sharpamsk.t7 (ie pretrained deepmask instead of pretrained sharpmask), as deepmask does indeed not have 'refs' key.
How did you get this sharpmask model? (this command: wget https://s3.amazonaws.com/deepmask/models/sharpmask/model.t7 -O sharpmask.t7 ?)
(sorry for this question, but its hard to debug since it does work in my side without touching anything...)

**Comment by northeastsquare** [comment]
md5sum sharpmask.t7 
b4db9112a422acf74c75c9c15bbc3987  sharpmask.t7

**Comment by poliveirap** [comment]
So yes, I think your sharpmask.t7 is actually deepmask, not sharpmask.
(from deepmask repository:)
md5sum pretrained/deepmask/model.t7
b4db9112a422acf74c75c9c15bbc3987  pretrained/deepmask/model.t7
md5sum pretrained/sharpmask/model.t7
1767d49a3150617b9abfcd054c135afb  pretrained/sharpmask/model.t7

Run  wget https://s3.amazonaws.com/deepmask/models/sharpmask/model.t7 -O sharpmask.t7
to download sharpmask (or use the correct sharpamsk model if you have somewhere) and it should work

**Comment by northeastsquare** [comment]
@poliveirap Thank you, I will try.

**Comment by poliveirap** [comment]
Did it work? Can I close this now?

**Comment by northeastsquare** [comment]
@poliveirap ,worked. but use some other image without target to run demo.lua, there is error:
/home/sam/torch/install/bin/luajit: ./demo.lua:83: calling 'select' on bad self (empty Tensor at /home/sam/torch/pkg/torch/generic/Tensor.c:380)
stack traceback:
	[C]: in function 'select'
	./demo.lua:83: in main chunk
	[C]: in function 'dofile'
	.../sam/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
