### ISSUE TITLE
what is data/annotations/pascal_train2007.json

### ISSUE THREAD

**Issue by samson-wang** [facebookresearch/multipathnet#12]
Hi all, I downloaded the VOC2007 dataset [VOCtrainval_06-Nov-2007.tar](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar). There is no json in it.
I think I should convert the voc annotation format to json. Could anyone give me a clue? Thanks!

**Comment by szagoruyko** [comment]
the link is in readme http://mscoco.org/external/, although it had https and was incorrect. Scroll down to PASCAL VOC and click download JSON.

**Comment by samson-wang** [comment]
Great! Thank you!

**Comment by sizhky** [comment]
Can't find it anymore!!

**Comment by m090009** [comment]
Same here @sizhky, but after some searching I found it at he `dataset/external` then scroll to the PASCAL VOC and there is a [link](https://storage.googleapis.com/coco-dataset/external/PASCAL_VOC.zip) to the COCO style PASCAL json

**Comment by atul219** [comment]
@m090009 The link which you have given is showing some kind of error.
![Screenshot (171)](https://user-images.githubusercontent.com/33904670/80287321-88c48200-874e-11ea-9106-54caceda645b.png)
