### ISSUE TITLE
multipathnet train Error

### ISSUE THREAD

**Issue by samson-wang** [facebookresearch/multipathnet#19]
When train multipathnet model. On the line https://github.com/facebookresearch/multipathnet/blob/master/models/multipathnet.lua#L26
`local data = torch.load'data/models/imagenet_pretrained_vgg.t7'`
and on the line https://github.com/facebookresearch/multipathnet/blob/master/models/multipathnet.lua#L32
`for i,v in ipairs{11,10,9,8,1} do classifier:remove(v) end`
However, the imagenet_pretrained_vgg.t7 mode's top has only 6 modules which leads to an error on the line https://github.com/torch/nn/blob/master/Sequential.lua#L29 .

**Comment by szagoruyko** [comment]
@samson-wang just remove this line for now, I will fix this in master later

**Comment by samson-wang** [comment]
@szagoruyko  It works! Thanks!
