### ISSUE TITLE
Where to download instances_val2014.json?

### ISSUE THREAD

**Issue by dearhoper** [facebookresearch/multipathnet#22]
Could anyone give me the link of instances_val2014.json? Is it under the COCO-TEXT or COCO-a?
Thanks!

**Comment by piconic** [comment]
It's here!! Hardest link to find lol
<img width="1080" alt="git" src="https://cloud.githubusercontent.com/assets/21302839/18940576/52b8e8f4-8644-11e6-99d8-e48aae2f4a8b.PNG">

**Comment by dearhoper** [comment]
Really? But the name of the json file that is downloaded from here is ILSVRC2014.

**Comment by piconic** [comment]
Oh! I'm really sorry. I made a mistake.
I confirmed that the link of the files is http://mscoco.org/dataset/#download > Annotations > 2014 Train/Val object instances [158MB].

**Comment by dearhoper** [comment]
Great!! It's here!! Thanks a lot.

**Comment by bfhaha** [comment]
The dataset has been moved to here 
https://cocodataset.org/#download
