### ISSUE TITLE
LuaJIT not enough memory

### ISSUE THREAD

**Issue by fanyix** [facebookresearch/multipathnet#39]
Hello,
I run into the following issue while running the training script for coco.
 
convert: ./data/annotations/instances_train2014.json --> .t7 [please be patient]	
/home/fanyix/torch/install/bin/luajit: not enough memory

It seems to be related to the memory limit of LuaJIT. But not sure if there is any solution to it. 
One potential workaround is to build my torch against plain Lua instead of LuaJIT. But then not sure if I can use fbpython anymore, since it seems modules in fblualib is supposed to work with LuaJIT. 

Thanks,
Fanyi

**Comment by szagoruyko** [comment]
That's a problem of https://github.com/pdollar/coco, if you have OS X at hand you can convert there and copy the file over. Mysteriously doesn't happen in OS X.
