### ISSUE TITLE
Out of memory :(

### ISSUE THREAD

**Issue by tzatter** [facebookresearch/multipathnet#4]
My environment setting is GTX960 2G, Ubuntu16.04, cuda8.0

I have tried to run demo

$ th demo.lua -img ./deepmask/data/testImage.jpg

...

THCudaCheck FAIL file=/home/tzatter/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=40 error=2 : out of memory
/home/tzatter/torch/install/bin/luajit: /home/tzatter/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 6 module of nn.Sequential:
In 1 module of nn.Sequential:
In 2 module of nn.Sequential:
/home/tzatter/torch/install/share/lua/5.1/nn/CAddTable.lua:13: cuda runtime error (2) : out of memory at /home/tzatter/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:40
stack traceback:
	[C]: in function 'resizeAs'
	/home/tzatter/torch/install/share/lua/5.1/nn/CAddTable.lua:13: in function </home/tzatter/torch/install/share/lua/5.1/nn/CAddTable.lua:9>
	[C]: in function 'xpcall'
	/home/tzatter/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/tzatter/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/tzatter/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/tzatter/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/tzatter/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/tzatter/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/tzatter/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/tzatter/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./deepmask/InferSharpMask.lua:103: in function 'forward'
	demo.lua:65: in main chunk
	[C]: in function 'dofile'
	...kasi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/tzatter/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/tzatter/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./deepmask/InferSharpMask.lua:103: in function 'forward'
	demo.lua:65: in main chunk
	[C]: in function 'dofile'
	...kasi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

**Comment by szagoruyko** [comment]
you can try a few things:
* run on a smaller image (-maxsize option)
* reduce number of scales and max scale (-si, -sf, -ss options)
* more advanced, plug [optnet](https://github.com/fmassa/optimize-net) here https://github.com/facebookresearch/deepmask/blob/master/InferDeepMask.lua#L79

**Comment by tzatter** [comment]
Hello Mr. szagoruyko

I have tried following below command
$th demo.lua -maxsize 128 -img ./deepmask/data/testImage.jpg
$th demo.lua -maxsize 128 -si -0.25 -sf 0.25 -ss 0.25 -img ./deepmask/data/testImage.jpg

but still out of memory

I have noticed my cudnn version is old
After upgraded I will try again

Thank you! (-人-)

**Comment by tzatter** [comment]
I need more memory but I am not a rich animal
I want GTX 1060 6GB (-人-)

**Comment by tzatter** [comment]
A square size image 256*256 has been successfully done at most
![res](https://cloud.githubusercontent.com/assets/17694190/18232083/5aa4eb20-7303-11e6-8b1c-551b08822aef.jpg)

**Comment by jfisher4** [comment]
Hi,
I am trying to run the sample code to test my installation and am getting an error most likely due to a path var not being set correctly. 


... init.lua:384: module 'deepmask.SharpMask' not found:No LuaRocks module found for deepmask.SharpMask
	no field package.preload['deepmask.SharpMask'] ...

Did I miss a step? Can you please help me figure out how to tell lua where deepmask resides?

Thanks,

Ryan

**Comment by tzatter** [comment]
Hello^^  check your directory tree the same as following below

$ sudo apt-get install tree
$ cd ~/multipathnet/
$ tree .
.
├── BatchProviderBase.lua
├── BatchProviderROI.lua
├── CONTRIBUTING.md
├── DataSetJSON.lua
├── ImageDetect.lua
├── LICENSE
├── Makefile
├── PATENTS
├── README.md
├── Tester_FRCNN.lua
├── config.lua
├── data
│   ├── annotations
│   │   ├── instances_train-val2014.zip
│   │   ├── instances_train2014.json
│   │   ├── instances_val2014.json
│   │   └── instances_val2014.t7
│   └── models
│       ├── deepmask.t7
│       ├── resnet18_integral_coco.t7
│       └── sharpmask.t7
├── data.lua
├── deepmask
│   ├── CONTRIBUTING.md
│   ├── DataLoader.lua
│   ├── DataSampler.lua
│   ├── DeepMask.lua
│   ├── InferDeepMask.lua
│   ├── InferSharpMask.lua
│   ├── LICENSE
│   ├── PATENTS
│   ├── README.md
│   ├── SharpMask.lua
│   ├── SpatialSymmetricPadding.lua
│   ├── TrainerDeepMask.lua
│   ├── TrainerSharpMask.lua
│   ├── computeProposals.lua
│   ├── data
│   │   ├── my01.jpg
│   │   ├── my02.jpg
│   │   ├── teaser.png
│   │   └── testImage.jpg
│   ├── evalPerImage.lua
│   ├── evalPerPatch.lua
│   ├── modelUtils.lua
│   ├── pretrained
│   │   ├── deepmask
│   │   │   └── model.t7
│   │   └── sharpmask
│   │       └── model.t7
│   ├── res.jpg
│   ├── train.lua
│   └── trainMeters.lua
├── demo.lua
├── donkey.lua
├── engines
│   ├── Optim.lua
│   └── fboptimengine.lua
├── fbcoco.lua
├── libnms.so
├── loaders
│   ├── concatloader.lua
│   ├── dataloader.lua
│   ├── loader.lua
│   └── narrowloader.lua
├── models
│   ├── alexnet.lua
│   ├── inceptionv3.lua
│   ├── model_utils.lua
│   ├── multipathnet.lua
│   ├── nin.lua
│   ├── resnet.lua
│   └── vgg.lua
├── modules
│   ├── BBoxNorm.lua
│   ├── BBoxRegressionCriterion.lua
│   ├── ContextRegion.lua
│   ├── ConvertFrom.lua
│   ├── Foveal.lua
│   ├── ImageTransformer.lua
│   ├── ModeSwitch.lua
│   ├── ModelParallelTable.lua
│   ├── NoBackprop.lua
│   ├── SelectBoxes.lua
│   ├── SequentialSplitBatch.lua
│   └── test.lua
├── nms.c
├── res.jpg
├── run_test.lua
├── scripts
│   ├── eval_coco.sh
│   ├── eval_fastrcnn_voc2007.sh
│   ├── train_coco.sh
│   ├── train_fastrcnn_voc2007.sh
│   └── train_multipathnet_coco.sh
├── test.lua
├── testCoco
│   ├── coco.lua
│   └── init.lua
├── test_runner.lua
├── train.lua
└── utils.lua

**Comment by neoxiang** [comment]
@tzatter Hi, I met the same problem like you said in your first comment. My graphic card is R470, GPU memory is 2GB too. Could you kindly tell what's your version of cudnn? And the sample picture the girl was your correct result with the upgrading of cudnn or upgrading of your graphic card? Thank you.

**Comment by tzatter** [comment]
My cudnn version is upgraded from the version 5.0 to the version5.1(cudnn-8.0-linux-x64-v5.1.tgz)

My GPU is the same as GTX960 2G

Important! I don't launch any GUI applications^^

**Comment by neoxiang** [comment]
@tzatter Yes, I followed your comment and crop it to a square image, then " -maxsize 128" is enabled and  I met another problem:
/home/ww/distro/install/bin/luajit: /home/ww/distro/install/share/lua/5.1/coco/CocoApi.lua:126: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/home/ww/distro/install/share/lua/5.1/coco/CocoApi.lua:126: in function '__init'
	/home/ww/distro/install/share/lua/5.1/torch/init.lua:91: in function </home/ww/distro/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'CocoApi'
	./loaders/loader.lua:19: in function 'DataLoader'
	/home/ww/multipathnet/DataSetJSON.lua:44: in function 'create'
	demo.lua:94: in main chunk
	[C]: in function 'dofile'
	.../ww/distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
I think it might be I put the unmatched file and used the unmatched filename.  
Could you kindly tell me whether you use this instruction with you file list tree as you show us before?
"local dataset = paths.dofile'./DataSetJSON.lua':create'coco_val2014'" 
Thank you！

**Comment by tzatter** [comment]
Do you have downloaded these files?
├── data
│   ├── annotations
│   │   ├── instances_train-val2014.zip
│   │   ├── instances_train2014.json
│   │   ├── instances_val2014.json
│   │   └── instances_val2014.t7

**Comment by neoxiang** [comment]
Yes, 

./data/annotations
├── ILSVRC2014_train.json
├── ILSVRC2014_val.json
├── instances_train2014.json
├── instances_train2014.t7
├── instances_train2014.zip
├── instances_val2014.json
├── instances_val2014.t7
├── instances_val2014.zip
├── pascal_test2007.json
├── pascal_train2007.json
├── pascal_train2012.json
├── pascal_val2007.json
└── pascal_val2012.json
And I also have modified config.lua as follow:
local coco_dir = '/home/ww/multipathnet/data/annotations'
return {
   coco_train2014 = paths.concat(coco_dir, 'instances_train2014'),
   coco_val2014 = paths.concat(coco_dir, 'instances_val2014'),
}
I have tried "local dataset = paths.dofile'./DataSetJSON.lua':create'coco_val2014'" and "local dataset = paths.dofile'./DataSetJSON.lua':create'coco_trainval2014'"

I got the same error info :
/home/ww/distro/install/bin/luajit: /home/ww/distro/install/share/lua/5.1/coco/CocoApi.lua:133: attempt to index field 'id' (a nil value)
stack traceback:
	/home/ww/distro/install/share/lua/5.1/coco/CocoApi.lua:133: in function '__init'
	/home/ww/distro/install/share/lua/5.1/torch/init.lua:91: in function </home/ww/distro/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'CocoApi'
	./loaders/loader.lua:19: in function 'DataLoader'
	/home/ww/multipathnet/DataSetJSON.lua:44: in function 'create'
	demo.lua:94: in main chunk
	[C]: in function 'dofile'
	.../ww/distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

@tzatter Thank you for your time and patience

**Comment by neoxiang** [comment]
finally succeed! I have changed model names back to "val.t7" . it works.
![res](https://cloud.githubusercontent.com/assets/22041671/18300237/e2c6d6ec-74f9-11e6-9f20-79a83add09d6.jpg)

**Comment by tzatter** [comment]
congratulation!^^
I am trying running on  g2.2xlarge of amazon ec2

**Comment by gpolaert** [comment]
I'm running out of memory too :) @tzatter, let give me your feedback about aws :)

I've encountered another issue, and I don't understand what's going on :'(.
Have you been faced to this one?
```
/bin/luajit: demo.lua:79: calling 'select' on bad self (empty Tensor at /home/gpolaert/torch/pkg/torch/generic/Tensor.c:380)
stack traceback:
        [C]: in function 'select'
        demo.lua:79: in main chunk
        [C]: in function 'dofile'
        ...aert/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405b80
```
Any idea?

**Comment by tzatter** [comment]
Hello^^
I'm a first-time user for amazon aws
Now I am reading tutorial lol
 I will contact you when something happens

**Comment by gpolaert** [comment]
Sure :)

**Comment by tzatter** [comment]
You have requested more instances (1) than your current instance limit of 0 allows for the specified instance type. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.

It could be tomorrow ^^

**Comment by neoxiang** [comment]
@gpolaert I have met the same issue. You can tried to crop your image to a square scale(same width and height), I hope it would be helpful.

**Comment by tzatter** [comment]
g2.2xlarge setting up took two hours

th demo.lua -np 5 -maxsize 800 -img ./deepmask/data/my04.jpg
![np05](https://cloud.githubusercontent.com/assets/17694190/18315608/8aa306a8-7552-11e6-9148-29afe5ad539a.jpg)

th demo.lua -np 10 -maxsize 800 -img ./deepmask/data/my04.jpg
![np10](https://cloud.githubusercontent.com/assets/17694190/18315622/9ab0c8aa-7552-11e6-838d-8fb1f740c972.jpg)

th demo.lua -np 50 -maxsize 800 -img ./deepmask/data/my04.jpg
![np50](https://cloud.githubusercontent.com/assets/17694190/18315643/a87fb34c-7552-11e6-90bc-2bda3736d7b0.jpg)

th demo.lua -np 100 -maxsize 800 -img ./deepmask/data/my04.jpg
![np100](https://cloud.githubusercontent.com/assets/17694190/18315670/ba46e69a-7552-11e6-83bb-8a4284ad0ad5.jpg)

Last image's parameters -np 100 -maxsize 800 was best

**Comment by jfisher4** [comment]
@tzatter Thanks very much for the help. After fixing my dir structure and installing one more dependency (luarocks install optnet) I have it working.

**Comment by tzatter** [comment]
@gpolaert I met the same issue. This error message means detected objects are not found

**Comment by tzatter** [comment]
Can I close this thread?
