### ISSUE TITLE
train ResNet-18 on COCO, got error

### ISSUE THREAD

**Issue by northeastsquare** [facebookresearch/multipathnet#5]
Hi, I train ResNet-18 on COCO according to README.md:
train_nGPU=1 test_nGPU=1 model=resnet resnet_path=./data/models/resnet/resnet-18.t7 ./scripts/train_coco.sh
By the way, I installed torch7 luajit, But train out of memory, so I 
cd ~/torch; 
TORCH_LUA_VERSION=LUA51 ./install.sh

I don't know this matter or not.
 
I got the following error:

Loading proposals at 	{
  1 : "/home/sam/src/multipathnet/data/proposals/coco/sharpmask/train.t7"
  2 : "/home/sam/src/multipathnet/data/proposals/coco/sharpmask/val.t7"
}
Done loading proposals	
# proposal images	123287	
# dataset images	118287	
# images	123287	
nImages	118287	
Loading proposals at 	{
  1 : "/home/sam/src/multipathnet/data/proposals/coco/sharpmask/train.t7"
  2 : "/home/sam/src/multipathnet/data/proposals/coco/sharpmask/val.t7"
}
Done loading proposals	
# proposal images	123287	
# dataset images	118287	
# images	123287	
nImages	118287	
/home/sam/torch/install/bin/lua: /home/sam/torch/install/share/lua/5.1/trepl/init.lua:384: ./loaders/loader.lua:39: expected cdata for arg #1
stack traceback:
	[C]: in function 'error'
	/home/sam/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	train.lua:121: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: ?

the whole output is :
[d.txt](https://github.com/facebookresearch/multipathnet/files/451094/d.txt)

**Comment by northeastsquare** [comment]
I ran ./clean.sh, in ~/torch, then 
TORCH_LUA_VERSION=LUA51 ./install.sh
and install the other package, but resualt is the same.

**Comment by szagoruyko** [comment]
@northeastsquare I pushed a patch for coco in https://github.com/facebookresearch/multipathnet/commit/e6b9e0dc68db5af4662be5f6c272c1db82ab514d, can you pull and try again?

**Comment by northeastsquare** [comment]
Yes, after pull, and use pure lua51 not luajit, and comment many 'tds', it start to train.Thank you.
