### ISSUE TITLE
problems installing fbpython and building PythonAPI

### ISSUE THREAD

**Issue by jfisher4** [facebookresearch/multipathnet#7]
Hi,

I had some problems when installing fbpython and found the problem to be that I did not have thpp installed. Should the readme be updated to warn other users? 

https://github.com/facebook/thpp 

Also I ran into issues when following the step where you cd into PythonAPI and make. Turns out I did not have Cython. I installed this using pip.

sudo apt-get install python-pip
sudo pip install Cython

I am still trying to locate all of the data in order to finish the setup but otherwise I think everything is going well. I hope this is helpful.

Thanks,

Ryan

**Comment by szagoruyko** [comment]
@jfisher4 thanks for the feedback! what problem did you have with fbpython? there was an issue with gtest that was resolved in https://github.com/facebook/thpp/commit/953baf6f0ab1011642e105b9ca4a6db9d565d2f3, it should install fine now

**Comment by jfisher4** [comment]
When I tried to do luarocks install fbpython the output was fussing about some THPP vars not existing. I do not seem so have the record of the error. I think the problem was that I was unaware of the dependency of thpp. 

Thanks,

Ryan
